---
name: Lint Code Base

on: # yamllint disable-line rule:truthy
  push: null
  pull_request: null

permissions: {}
jobs:
  build:
    name: Lint
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read
      statuses: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Super-linter
        # uses: super-linter/super-linter/slim@12150456a73e248bdc94d0794898f94e23127c88 # 7.4.0
        uses: super-linter/super-linter/slim@2bdd90ed3262e023ac84bf8fe35dc480721fc1f2 # v8.2.1
        # Can't move on to super-linter v8.x yet due to Drupal core still using airbnb-base eslint config
        # https://www.drupal.org/project/drupal/issues/3440225
        # https://github.com/super-linter/super-linter/blob/main/docs/upgrade-guide.md#removed-eslint-plugins-and-configurations

        env:
          LINTER_RULES_PATH: .github/linters
          VALIDATE_BIOME_FORMAT: false
          VALIDATE_JAVASCRIPT_PRETTIER: false
          VALIDATE_JSCPD: false
          VALIDATE_JSON_PRETTIER: false
          VALIDATE_PHP_PSALM: false
          VALIDATE_PHP_PHPCS: false
          # YAML is validated via eslint plugin for Drupal
          VALIDATE_YAML_PRETTIER: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
