server {
    listen 80;
    server_name localhost;
    root /var/www/html/web; # Point to your Drupal web root

    location = /favicon.ico {
        log_not_found off;
        access_log off;
    }

    location = /robots.txt {
        allow all;
        log_not_found off;
        access_log off;
    }

    # Main Drupal rewrite rules
    location / {
        try_files $uri /index.php?$query_string;
    }

    # Pass PHP scripts to the PHP-FPM container
    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass app:9000; # 'app' is the service name in docker-compose.yml
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }

    # Block access to sensitive files
    location ~* \.(engine|inc|info|install|make|module|profile|test|po|sh|.*sql|theme|twig|tpl(\.php)?|xtmpl)$|/(\.git|cron|UPGRADE|README)\.txt$ {
        deny all;
    }

    location ~ /\. {
        deny all;
    }
}